site_name: KRYZA Diamond Chain Docs
site_description: KRYZA Diamond Chain Technology Documentation
site_author: KRYZA Diamond Chain Community
site_url: https://docs.kryzascan.com
use_directory_urls: false
theme:
  name: material
  logo: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: amber
    scheme: slate
    accent: yellow 
  feature:
    tabs: true
extra_css:
       - stylesheets/dark_theme.css
       - stylesheets/codehilite.css  
repo_name: KRYZA Diamond
repo_url: https://github.com/

nav:
  - Home: index.md
  - KRYZA Diamond Chain:
    - Introduction: smart-chain/guides/nc-intro.md
    - Concepts:
      - Consensus: smart-chain/guides/concepts/consensus.md
      - Genesis File: smart-chain/guides/concepts/genesis.md
    - Ecosystem: https://github.com/ 
    - KRYZA Diamond Chain Mainnet Explorer: https://kryzascan.com/
    - KRYZA Diamond Chain Testnet Explorer: https://testnet-explorer.kryzascan.com/
    - Wallet: smart-chain/wallet.md
  - KRYZA Diamond Chain Developers:
    - General:
      - Create Wallet: smart-chain/developer/create-wallet.md
      - Smart Contract: https://solidity.readthedocs.io/en/v0.7.1/
      - Remix : https://remix.ethereum.org/
      - Web3JS: https://web3js.readthedocs.io/en/v1.2.11/
      - Truffle: https://www.trufflesuite.com/docs/teams/quickstart
    - Ecosystem: https://github.com/
    - Deploy:
      - Remix: smart-chain/developer/deploy/remix.md
      - Truffle: smart-chain/developer/deploy/truffle.md
      - HardHat: smart-chain/developer/deploy/hardhat.md
    - Tools:   
      - Wallet Provider for DApps: smart-chain/wallet/arkane-developer.md
    - KRC20 Tokens:
      - Introduction: smart-chain/developer/KRC20.md
      - Issue Token: smart-chain/developer/issue-KRC20.md
    - Blockchain Details:
      - KRYZA Diamond Chain Fullnode: smart-chain/developer/fullnode.md      
      - RPC: smart-chain/developer/rpc.md
    - Tutorial:
      - Deploy NFT:  smart-chain/developer/KRC721.md      
      - Local KRYZA Diamond Network: smart-chain/developer/deploy/local.md
  - Wallets:
    - KRYZA Diamond Chain Wallet Support: smart-chain/wallet.md
  - KRYZA Diamond Chain Explorer: https://kryzascan.com
  - KRYZA Diamond Chain Faucet: https://faucet.kryzascan.com
  - The KRYZA Diamond Chain Telegram Group : https://t.me/kryzaglobal
  - Twitter: https://twitter.com/KryzaToken
  - FAQ:
    - KRYZA Diamond Chain FAQ:
      - General:
        - Info: faq/nc/general.md
        - KRYZA Diamond Chain: faq/nc/nc.md
        - Ecosystem: faq/nc/eco.md
      - Token:
        - Intro: faq/nc/token.md
        - KRC20: faq/nc/krc20.md
    - Contributing: CONTRIBUTING.md


markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.superfences
    - codehilite